import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
#config :phoenix_react, PhoenixReactWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"


config :phoenix_react, PhoenixReactWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  #http: [ip: {127, 0, 0, 1}, port: 4000],
  http: [ip: {0, 0, 0, 0}, port: 4000],
  #url: [host: "hw2.edgerock1.com"],
  check_origin: :conn,
  #code_reloader: true,
  #debug_errors: true,
  secret_key_base: "UAdrHQA4rxA9EWT6zwBuyunGWP1mygH621u5tkwOF3Vz6PAvfh8kjRLVe+AYbWnG"



# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: PhoenixReact.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.


# Configure your database
config :phoenix_react, PhoenixReact.Repo,
  username: "postgres",
  password: "postgresSuperUserPsw",
  hostname: "localhost",
  database: "phoenix_react_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10
